version: '3.4'

services:
  client:
    image: client
    build:
      context: web-api/client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8010:8010
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
